### ISSUE TITLE
Compile Sponsor pages

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#30]
Please convert the sponsor pages to be YAML that is compiled to show the images rather than markdown. I would suggest the following YAML to produce https://kubernetescommunitydays.org/events/2020-bouvet-island/sponsors/

Categories should be displayed in the order shown, but items within a category should be displayed alphabetically.

```yml
sponsors:
  - category:
    name: Diamond
    items:
      - item:
        name: Oceanic Airways
        url: 'https://en.wikipedia.org/wiki/Oceanic_Airlines'
        logo: sponsor-oceanic-airways.svg
  - category:
    name: Platinum
    items:
      - item:
        name: BnL
        url: 'https://en.wikipedia.org/wiki/List_of_Pixar_film_references#Buy_n_Large_(BnL)'
        logo: sponsor-bnl.svg
```
