### ISSUE TITLE
Code of Conduct and required event metadata

### ISSUE THREAD

**Issue by dankohn** [cncf/kubernetes-community-days#46]
Please create a `Code of Conduct` menu that shows as the final item on all pages. The text should be copied from (not a link to) https://events.linuxfoundation.org/code-of-conduct/. 

Please require the following metadata for all KCD events, entered in `_index.md`:
```yaml
organizers-email: organizers-bouvet-island-2020@kubernetescommunitydays.org
local-law-enforcement: 112
medical-emergency: 112
```
Then, please display these at the bottom of https://kubernetescommunitydays.org/events/2020-bouvet-island/code-of-conduct/
and other Code of Conduct pages for Bouvet Island.

So, the content of the page will be the same, except for the contact info that will be different for individual events.
